<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0220ENSkillsNetwork900-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

<h1>Extracting and Visualizing Stock Data</h1>
<h2>Description</h2>

Extracting essential data from a dataset and displaying it is a necessary part of data science; therefore individuals can make correct decisions based on the data. In this assignment, you will extract some stock data, you will then display this data in a graph.

<h2>Table of Contents</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li>Define a Function that Makes a Graph</li>
        <li>Question 1: Use yfinance to Extract Stock Data</li>
        <li>Question 2: Use Webscraping to Extract Tesla Revenue Data</li>
        <li>Question 3: Use yfinance to Extract Stock Data</li>
        <li>Question 4: Use Webscraping to Extract GME Revenue Data</li>
        <li>Question 5: Plot Tesla Stock Graph</li>
        <li>Question 6: Plot GameStop Stock Graph</li>
    </ul>
<p>
    Estimated Time Needed: <strong>30 min</strong></p>
</div>

<hr>

***Note***:- If you are working in IBM Cloud Watson Studio, please replace the command for installing nbformat from `!pip install nbformat==4.2.0` to simply `!pip install nbformat`

In [53]:
!pip install yfinance
!mamba install bs4==4.10.0 -y
!pip install nbformat==5.7.0
!mamba install html5lib==1.1 -y
!pip install bs4

Collecting yfinance
  Downloading yfinance-0.2.31-py2.py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.6/65.6 kB 12.0 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.3.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance) (1.3.5)
Requirement already satisfied: numpy>=1.16.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance) (1.21.6)
Collecting requests>=2.31 (from yfinance)
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 12.5 MB/s eta 0:00:00
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.11-py3-none-any.whl (8.5 kB)
Requirement already satisfied: lxml>=4.9.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance) (4.9.2)
Collecting appdirs>=1.4.4 (from yfinance)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: pytz>=2022.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance) (2023.3)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.3.8-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 22.5 MB/s eta 0:00:00
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.16.3.tar.gz (928 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 928.0/928.0 kB 29.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from yfinance) (4.11.1)
Collecting html5lib>=1.1 (from yfinance)
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 20.5 MB/s eta 0:00:00
Requirement already satisfied: soupsieve>1.2 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.3.2.post1)
Requirement already satisfied: six>=1.9 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.31->yfinance) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.31->yfinance) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.31->yfinance) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from requests>=2.31->yfinance) (2023.5.7)
Building wheels for collected packages: peewee
  Building wheel for peewee (pyproject.toml) ... done
  Created wheel for peewee: filename=peewee-3.16.3-py3-none-any.whl size=135501 sha256=9c3e907705afb83ca69171d6ee2411fc40b51a57923512f83f2712b22655cba3
  Stored in directory: /home/jupyterlab/.cache/pip/wheels/40/c1/c7/c5a1a24806ef61fd7a92027d49199fc5be46e6becb1eadfd15
Successfully built peewee
Installing collected packages: peewee, multitasking, appdirs, requests, html5lib, frozendict, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.29.0
    Uninstalling requests-2.29.0:
      Successfully uninstalled requests-2.29.0
Successfully installed appdirs-1.4.4 frozendict-2.3.8 html5lib-1.1 multitasking-0.0.11 peewee-3.16.3 requests-2.31.0 yfinance-0.2.31

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['bs4==4.10.0']

[+] 0.0s
[+] 0.1s
pkgs/main/linux-64 ━━━━━━━━━━━━━━━╸━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s
pkgs/main/noarch   ━━━━━━━━━╸━━━━━━━━━━━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s
pkgs/r/linux-64    ━━━━━━━╸━━━━━━━━━━━━━━━╸━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s
pkgs/r/noarch      ━━━╸━━━━━━━━━━━━━━━╸━━━━━   0.0 B /  ??.?MB @  ??.?MB/s  0.1s[+] 0.2s
pkgs/main/linux-64 ━━━━━━━━━╸━━━━━━━━━━━━━━━  94.2kB /  ??.?MB @ 613.7kB/s  0.2s
pkgs/main/noarch   ━━━━━━━━━━━━╸━━━━━━━━━━━━  12.3kB /  ??.?MB @  80.3kB/s  0.2s
pkgs/r/linux-64    ━━━━━━━━━╸━━━━━━━━━━━━━━━  57.4kB /  ??.?MB @ 374.7kB/s  0.2s
pkgs/r/noarch      ━━━━━╸━━━━━━━━━━━━━━━╸━━━  57.4kB /  ??.?MB @ 373.7kB/s  0.2s[+] 0.3s
pkgs/main/linux-64 ━━━━━━━━━━━━╸━━━━━━━━━━━━ 577.5kB /  ??.?MB @   2.3MB/s  0.3s
pkgs/main/noarch   ━━━━━━━━━━━━━━╸━━━━━━━━━━ 540.7kB /  ??.?MB @   2.1MB/s  0.3s
pkgs/r/linux-64    ━━━━━━━━━━━╸━━━━━━━━━━━━━ 565.3kB /  ??.?MB @   2.2MB/s  0.3s
pkgs/r/noarch      ━━━━━━━╸━━━━━━━━━━━━━━━╸━ 606.2kB /  ??.?MB @   2.4MB/s  0.3spkgs/main/noarch                                   852.8kB @   2.7MB/s  0.3s
[+] 0.4s
pkgs/main/linux-64 ━━━━━━━━━━━━━━╸━━━━━━━━━   1.2MB @   3.3MB/s             0.4s
pkgs/r/linux-64    ━━━━━━━━━━━━━╸━━━━━━━━━━   1.2MB @   3.2MB/s             0.4s
pkgs/r/noarch      ━━━━━━━━━━━━━━━━━━━━━━━━   1.3MB @   3.4MB/s Finalizing  0.4spkgs/r/noarch                                      @   3.4MB/s  0.4s
pkgs/r/linux-64                                    @   3.3MB/s  0.5s
[+] 0.5s
pkgs/main/linux-64 ╸━━━━━━━━━━━━━━━╸━━━━━━━━   1.9MB /  ??.?MB @   3.9MB/s  0.5s[+] 0.6s
pkgs/main/linux-64 ━━━╸━━━━━━━━━━━━━━━╸━━━━━   2.5MB /  ??.?MB @   4.2MB/s  0.6s[+] 0.7s
pkgs/main/linux-64 ━━━━━╸━━━━━━━━━━━━━━━╸━━━   3.1MB /  ??.?MB @   4.4MB/s  0.7s[+] 0.8s
pkgs/main/linux-64 ━━━━━━━━╸━━━━━━━━━━━━━━━━   3.6MB /  ??.?MB @   4.5MB/s  0.8s[+] 0.9s
pkgs/main/linux-64 ━━━━━━━━━━╸━━━━━━━━━━━━━━   4.1MB /  ??.?MB @   4.6MB/s  0.9s[+] 1.0s
pkgs/main/linux-64 ━━━━━━━━━━━╸━━━━━━━━━━━━━   4.4MB /  ??.?MB @   4.7MB/s  1.0s[+] 1.1s
pkgs/main/linux-64 ━━━━━━━━━━━━━━╸━━━━━━━━━━   5.0MB /  ??.?MB @   4.8MB/s  1.1s[+] 1.2s
pkgs/main/linux-64 ━━━━━━━━╸━━━━━━━━━━━━━━━━   5.6MB /  ??.?MB @   4.9MB/s  1.2s[+] 1.3s
pkgs/main/linux-64 ━━━━━━━━━╸━━━━━━━━━━━━━━━   5.9MB /  ??.?MB @   4.9MB/s  1.3s[+] 1.4s
pkgs/main/linux-64 ━━━━━━━━━━━━━━━━━━━━━━━━   6.1MB @   4.9MB/s Finalizing  1.4spkgs/main/linux-64                                 @   4.9MB/s  1.4s

Pinned packages:
  - python 3.7.*


Transaction

  Prefix: /home/jupyterlab/conda/envs/python

  Updating specs:

   - bs4==4.10.0
   - ca-certificates
   - certifi
   - openssl


  Package               Version  Build         Channel                 Size
─────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────

  + bs4                  4.10.0  hd3eb1b0_0    pkgs/main/noarch        10kB

  Upgrade:
─────────────────────────────────────────────────────────────────────────────

  - ca-certificates    2023.5.7  hbcca054_0    conda-forge
  + ca-certificates  2023.08.22  h06a4308_0    pkgs/main/linux-64     125kB
  - openssl              1.1.1t  h0b41bf4_0    conda-forge
  + openssl              1.1.1w  h7f8727e_0    pkgs/main/linux-64       4MB

  Downgrade:
─────────────────────────────────────────────────────────────────────────────

  - beautifulsoup4       4.11.1  pyha770c72_0  conda-forge
  + beautifulsoup4       4.10.0  pyh06a4308_0  pkgs/main/noarch        87kB

  Summary:

  Install: 1 packages
  Upgrade: 2 packages
  Downgrade: 1 packages

  Total download: 4MB

─────────────────────────────────────────────────────────────────────────────


[+] 0.0s
Downloading  (1) ━━━━━━━━━━━━━━━━━━━━━━━   0.0 B beautifulsoup4             0.0s
Extracting       ━━━━━━━━━━━━━━━━━━━━━━━       0                            0.0s[+] 0.1s
Downloading  (4) ━━━━━━━━━━━━━━━━━━━━━━━   0.0 B beautifulsoup4             0.1s
Extracting       ━━━━━━━━━━━━━━━━━━━━━━━       0                            0.0sbeautifulsoup4                                      86.6kB @ 594.9kB/s  0.1s
ca-certificates                                    125.5kB @ 823.8kB/s  0.2s
bs4                                                 10.2kB @  66.8kB/s  0.2s
[+] 0.2s
Downloading  (1) ╸━━━━━━━━━━━━━━━━━━━━━━ 222.3kB openssl                    0.2s
Extracting   (3) ━━━━━━━━━━━━╸━━━━━━━━━━       0 beautifulsoup4             0.0sopenssl                                              3.9MB @  17.0MB/s  0.2s
[+] 0.3s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━╸━━━━━━━━━━━━━━━       0 beautifulsoup4             0.1s[+] 0.4s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━╸━━━━━━━━━━━━━━       0 beautifulsoup4             0.2s[+] 0.5s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━╸━━━━━━━━━━━━━       0 beautifulsoup4             0.3s[+] 0.6s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━━━╸━━━━━━━━━━━       0 bs4                        0.4s[+] 0.7s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━━━━╸━━━━━━━━━━       0 bs4                        0.5s[+] 0.8s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━━━━━╸━━━━━━━━━       0 bs4                        0.6s[+] 0.9s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━━━━━━╸━━━━━━━━       0 bs4                        0.7s[+] 1.0s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━━━━━━━━╸━━━━━━━       0 ca-certificates            0.8s[+] 1.1s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ╸━━━━━━━━━━━━━━━╸━━━━━━       0 ca-certificates            0.9s[+] 1.2s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━╸━━━━━━━━━━━━━━━╸━━━━━       0 ca-certificates            1.0s[+] 1.3s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━╸━━━━━━━━━━━━━━━╸━━━━       0 ca-certificates            1.1s[+] 1.4s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━╸━━━━━━━━━━━━━━━╸━━━       0 openssl                    1.2s[+] 1.5s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━╸━━━━━━━━━━━━━━━╸━━       0 openssl                    1.3s[+] 1.6s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━╸━━━━━━━━━━━━━━━━       0 openssl                    1.4s[+] 1.7s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━╸━━━━━━━━━━━━━━━       0 openssl                    1.5s[+] 1.8s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (4) ━━━━━━━━╸━━━━━━━━━━━━━━       0 beautifulsoup4             1.6s[+] 1.9s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (3) ━━━━╸━━━━━━━━━━━━━━━━━━       1 bs4                        1.7s[+] 2.0s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (3) ━━━━╸━━━━━━━━━━━━━━━━━━       1 bs4                        1.8s[+] 2.1s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (2) ━━━━━━━━━━╸━━━━━━━━━━━━       2 ca-certificates            1.9s[+] 2.2s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   4.1MB                            0.3s
Extracting   (1) ━━━━━━━━━━━━━━━━╸━━━━━━       3 openssl                    2.0s
Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting nbformat==5.7.0
  Downloading nbformat-5.7.0-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 12.8 MB/s eta 0:00:00
Requirement already satisfied: fastjsonschema in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==5.7.0) (2.16.3)
Requirement already satisfied: importlib-metadata>=3.6 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==5.7.0) (4.11.4)
Requirement already satisfied: jsonschema>=2.6 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==5.7.0) (4.17.3)
Requirement already satisfied: jupyter-core in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==5.7.0) (4.12.0)
Requirement already satisfied: traitlets>=5.1 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from nbformat==5.7.0) (5.9.0)
Requirement already satisfied: zipp>=0.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from importlib-metadata>=3.6->nbformat==5.7.0) (3.15.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from importlib-metadata>=3.6->nbformat==5.7.0) (4.5.0)
Requirement already satisfied: attrs>=17.4.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema>=2.6->nbformat==5.7.0) (23.1.0)
Requirement already satisfied: importlib-resources>=1.4.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema>=2.6->nbformat==5.7.0) (5.12.0)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema>=2.6->nbformat==5.7.0) (1.3.10)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from jsonschema>=2.6->nbformat==5.7.0) (0.19.3)
Installing collected packages: nbformat
  Attempting uninstall: nbformat
    Found existing installation: nbformat 5.8.0
    Uninstalling nbformat-5.8.0:
      Successfully uninstalled nbformat-5.8.0
Successfully installed nbformat-5.7.0

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['html5lib==1.1']

pkgs/main/linux-64                                          Using cache
pkgs/main/noarch                                            Using cache
pkgs/r/linux-64                                             Using cache
pkgs/r/noarch                                               Using cache

Pinned packages:
  - python 3.7.*


Transaction

  Prefix: /home/jupyterlab/conda/envs/python

  Updating specs:

   - html5lib==1.1
   - ca-certificates
   - certifi
   - openssl


  Package         Version  Build         Channel                Size
──────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────

  + html5lib          1.1  pyhd3eb1b0_0  pkgs/main/noarch       93kB
  + webencodings    0.5.1  py37_1        pkgs/main/linux-64     20kB

  Summary:

  Install: 2 packages

  Total download: 113kB

──────────────────────────────────────────────────────────────────────


[+] 0.0s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━   0.0 B                            0.0s
Extracting       ━━━━━━━━━━━━━━━━━━━━━━━       0                            0.0s[+] 0.1s
Downloading  (2) ━━━━━━━━━━━━━━━━━━━━━━━   0.0 B html5lib                   0.0s
Extracting       ━━━━━━━━━━━━━━━━━━━━━━━       0                            0.0swebencodings                                        19.6kB @ 146.4kB/s  0.1s
html5lib                                            93.0kB @ 659.2kB/s  0.1s
[+] 0.2s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━ 112.6kB                            0.1s
Extracting   (2) ━━━━━╸━━━━━━━━━━━━━━━╸━       0 html5lib                   0.0s[+] 0.3s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━ 112.6kB                            0.1s
Extracting   (2) ━━━━━━╸━━━━━━━━━━━━━━━━       0 html5lib                   0.1s[+] 0.4s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━ 112.6kB                            0.1s
Extracting   (2) ━━━━━━━━╸━━━━━━━━━━━━━━       0 html5lib                   0.2s[+] 0.5s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━ 112.6kB                            0.1s
Extracting   (2) ━━━━━━━━━╸━━━━━━━━━━━━━       0 html5lib                   0.3s[+] 0.6s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━ 112.6kB                            0.1s
Extracting   (2) ━━━━━━━━━━╸━━━━━━━━━━━━       0 webencodings               0.4s[+] 0.7s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━ 112.6kB                            0.1s
Extracting   (2) ━━━━━━━━━━━╸━━━━━━━━━━━       0 webencodings               0.5s[+] 0.8s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━ 112.6kB                            0.1s
Extracting   (2) ━━━━━━━━━━━━╸━━━━━━━━━━       0 webencodings               0.6s[+] 0.9s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━ 112.6kB                            0.1s
Extracting   (2) ━━━━━━━╸━━━━━━━━━━━━━━━       0 webencodings               0.7s[+] 1.0s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━ 112.6kB                            0.1s
Extracting   (2) ━━━━━━━━╸━━━━━━━━━━━━━━       0 html5lib                   0.8s[+] 1.1s
Downloading      ━━━━━━━━━━━━━━━━━━━━━━━ 112.6kB                            0.1s
Extracting   (2) ━━━━━━━━━╸━━━━━━━━━━━━━       0 html5lib                   0.9s
Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: beautifulsoup4 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from beautifulsoup4->bs4) (2.3.2.post1)
Building wheels for collected packages: bs4
  Building wheel for bs4 (setup.py) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1257 sha256=b3eaf22a85b925d51ed7838e555d7c66cfd6d5f7e1b10f07bdb3a989bd61021e

In [54]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go 
from plotly.subplots import make_subplots

## Define Graphing Function

In this section, we define the function `make_graph`. You don't have to know how the function works, you should only care about the inputs. It takes a dataframe with stock data (dataframe must contain Date and Close columns), a dataframe with revenue data (dataframe must contain Date and Revenue columns), and the name of the stock.

In [2]:
def make_graph(stock_data, revenue_data, stock):
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, subplot_titles=("Historical Share Price", "Historical Revenue"), vertical_spacing = .3)
    stock_data_specific = stock_data[stock_data.Date <= '2021--06-14']
    revenue_data_specific = revenue_data[revenue_data.Date <= '2021-04-30']
    fig.add_trace(go.Scatter(x=pd.to_datetime(stock_data_specific.Date, infer_datetime_format=True), y=stock_data_specific.Close.astype("float"), name="Share Price"), row=1, col=1)
    fig.add_trace(go.Scatter(x=pd.to_datetime(revenue_data_specific.Date, infer_datetime_format=True), y=revenue_data_specific.Revenue.astype("float"), name="Revenue"), row=2, col=1)
    fig.update_xaxes(title_text="Date", row=1, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)
    fig.update_yaxes(title_text="Price ($US)", row=1, col=1)
    fig.update_yaxes(title_text="Revenue ($US Millions)", row=2, col=1)
    fig.update_layout(showlegend=False,
    height=900,
    title=stock,
    xaxis_rangeslider_visible=True)
    fig.show()

## Question 1: Use yfinance to Extract Stock Data

Using the `Ticker` function enter the ticker symbol of the stock we want to extract data on to create a ticker object. The stock is Tesla and its ticker symbol is `TSLA`.

In [55]:
tesla=yf.Ticker("TSLA")

Using the ticker object and the function `history` extract stock information and save it in a dataframe named `tesla_data`. Set the `period` parameter to `max` so we get information for the maximum amount of time.

In [56]:
tesla_data = tesla . history(period = 'max')
tesla_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0
...,...,...,...,...,...,...,...
2023-10-02 00:00:00-04:00,244.809998,254.279999,242.619995,251.600006,123810400,0.0,0.0
2023-10-03 00:00:00-04:00,248.610001,250.020004,244.449997,246.529999,101985300,0.0,0.0
2023-10-04 00:00:00-04:00,248.139999,261.859985,247.600006,261.160004,129721600,0.0,0.0
2023-10-05 00:00:00-04:00,260.000000,263.600006,256.250000,260.049988,119159200,0.0,0.0
2023-10-06 00:00:00-04:00,253.979996,261.649994,250.649994,260.529999,117947000,0.0,0.0

**Reset the index** using the `reset_index(inplace=True)` function on the tesla_data DataFrame and display the first five rows of the `tesla_data` dataframe using the `head` function. Take a screenshot of the results and code from the beginning of Question 1 to the results below.

In [7]:
tesla_data.reset_index(inplace=True)
tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29,1.266667,1.666667,1.169333,1.592667,281494500,0,0.0
1,2010-06-30,1.719333,2.028000,1.553333,1.588667,257806500,0,0.0
2,2010-07-01,1.666667,1.728000,1.351333,1.464000,123282000,0,0.0
3,2010-07-02,1.533333,1.540000,1.247333,1.280000,77097000,0,0.0
4,2010-07-06,1.333333,1.333333,1.055333,1.074000,103003500,0,0.0

## Question 2: Use Webscraping to Extract Tesla Revenue Data

Use the `requests` library to download the webpage https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm Save the text of the response as a variable named `html_data`.

In [28]:
import requests
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm"
html_data = requests.get(url)
print(html_data)

<Response [200]>

Parse the html data using `beautiful_soup`.

In [30]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_data.text, 'html.parser')

Using `BeautifulSoup` or the `read_html` function extract the table with `Tesla Revenue` and store it into a dataframe named `tesla_revenue`. The dataframe should have columns `Date` and `Revenue`.

In [33]:
import pandas as pd
tesla_tables = soup.find_all('table')

for index,table in enumerate(tesla_tables):
    if ("Tesla Quarterly Revenue" in str(table)):
        tesla_table_index = index

tesla_revenue = pd.DataFrame(columns=["Date", "Revenue"])

for row in tesla_tables[tesla_table_index].tbody.find_all("tr"):
    col = row.find_all("td")
    if (col !=[]):
        date = col[0].text
        revenue = col[1].text.replace("$", "").replace(",", "")
        tesla_revenue = tesla_revenue.append({"Date" : date, "Revenue" : revenue}, ignore_index=True)

<details><summary>Click here if you need help locating the table</summary>

```
    
Below is the code to isolate the table, you will now need to loop through the rows and columns like in the previous lab
    
soup.find_all("tbody")[1]
    
If you want to use the read_html function the table is located at index 1


```

</details>

Execute the following line to remove the comma and dollar sign from the `Revenue` column.

In [ ]:
tesla_revenue["Revenue"] = tesla_revenue['Revenue'].str.replace(',',"").str.replace('$',"")

Execute the following lines to remove an null or empty strings in the Revenue column.

Display the last 5 row of the `tesla_revenue` dataframe using the `tail` function. Take a screenshot of the results.

In [34]:
tesla_revenue.dropna(inplace=True)

tesla_revenue = tesla_revenue[tesla_revenue['Revenue'] != ""]
tesla_revenue

          Date Revenue
0   2022-09-30   21454
1   2022-06-30   16934
2   2022-03-31   18756
3   2021-12-31   17719
4   2021-09-30   13757
5   2021-06-30   11958
6   2021-03-31   10389
7   2020-12-31   10744
8   2020-09-30    8771
9   2020-06-30    6036
10  2020-03-31    5985
11  2019-12-31    7384
12  2019-09-30    6303
13  2019-06-30    6350
14  2019-03-31    4541
15  2018-12-31    7226
16  2018-09-30    6824
17  2018-06-30    4002
18  2018-03-31    3409
19  2017-12-31    3288
20  2017-09-30    2985
21  2017-06-30    2790
22  2017-03-31    2696
23  2016-12-31    2285
24  2016-09-30    2298
25  2016-06-30    1270
26  2016-03-31    1147
27  2015-12-31    1214
28  2015-09-30     937
29  2015-06-30     955
30  2015-03-31     940
31  2014-12-31     957
32  2014-09-30     852
33  2014-06-30     769
34  2014-03-31     621
35  2013-12-31     615
36  2013-09-30     431
37  2013-06-30     405
38  2013-03-31     562
39  2012-12-31     306
40  2012-09-30      50
41  2012-06-30      27
42  2012-03-31      30
43  2011-12-31      39
44  2011-09-30      58
45  2011-06-30      58
46  2011-03-31      49
47  2010-12-31      36
48  2010-09-30      31
49  2010-06-30      28
50  2010-03-31      21
52  2009-09-30      46
53  2009-06-30      27

In [31]:
tesla_revenue.tail(5)

          Date Revenue
48  2010-09-30      31
49  2010-06-30      28
50  2010-03-31      21
52  2009-09-30      46
53  2009-06-30      27

## Question 3: Use yfinance to Extract Stock Data

Using the `Ticker` function enter the ticker symbol of the stock we want to extract data on to create a ticker object. The stock is GameStop and its ticker symbol is `GME`.

In [58]:
import yfinance as yf
gme = yf.Ticker('GME')

gme_data = gme.history(period='max')Using the ticker object and the function `history` extract stock information and save it in a dataframe named `gme_data`. Set the `period` parameter to `max` so we get information for the maximum amount of time.

In [59]:
gme_data = gme.history(period='max')
print(gme_data)

                                Open       High        Low      Close  \
Date
2002-02-13 00:00:00-05:00   1.620128   1.693350   1.603296   1.691666
2002-02-14 00:00:00-05:00   1.712707   1.716073   1.670626   1.683250
2002-02-15 00:00:00-05:00   1.683250   1.687458   1.658001   1.674834
2002-02-19 00:00:00-05:00   1.666417   1.666417   1.578047   1.607504
2002-02-20 00:00:00-05:00   1.615920   1.662209   1.603296   1.662209
...                              ...        ...        ...        ...
2023-10-02 00:00:00-04:00  16.299999  16.309999  15.260000  15.390000
2023-10-03 00:00:00-04:00  15.290000  15.290000  14.570000  14.600000
2023-10-04 00:00:00-04:00  14.770000  14.940000  14.440000  14.870000
2023-10-05 00:00:00-04:00  14.700000  14.980000  14.580000  14.710000
2023-10-06 00:00:00-04:00  14.590000  15.260000  14.580000  15.080000

                             Volume  Dividends  Stock Splits
Date
2002-02-13 00:00:00-05:00  76216000        0.0           0.0
2002-02-14 00:00:00-05:00  11021600        0.0           0.0
2002-02-15 00:00:00-05:00   8389600        0.0           0.0
2002-02-19 00:00:00-05:00   7410400        0.0           0.0
2002-02-20 00:00:00-05:00   6892800        0.0           0.0
...                             ...        ...           ...
2023-10-02 00:00:00-04:00   6087700        0.0           0.0
2023-10-03 00:00:00-04:00   4510300        0.0           0.0
2023-10-04 00:00:00-04:00   2586400        0.0           0.0
2023-10-05 00:00:00-04:00   1945100        0.0           0.0
2023-10-06 00:00:00-04:00   2458300        0.0           0.0

[5450 rows x 7 columns]

**Reset the index** using the `reset_index(inplace=True)` function on the gme_data DataFrame and display the first five rows of the `gme_data` dataframe using the `head` function. Take a screenshot of the results and code from the beginning of Question 3 to the results below.

In [48]:
gme_data.reset_index(inplace=True)
gme_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13,1.620128,1.693350,1.603296,1.691666,76216000,0.0,0.0
1,2002-02-14,1.712707,1.716073,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15,1.683251,1.687459,1.658002,1.674834,8389600,0.0,0.0
3,2002-02-19,1.666417,1.666417,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20,1.615920,1.662210,1.603296,1.662210,6892800,0.0,0.0

## Question 4: Use Webscraping to Extract GME Revenue Data

Use the `requests` library to download the webpage https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html. Save the text of the response as a variable named `html_data`.

In [57]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html"
html_data = requests.get(url)
print(html_data)

<Response [200]>

Parse the html data using `beautiful_soup`.

In [48]:
soup = BeautifulSoup(html_data.text,"html.parser")

In [61]:

gme_tables = soup.find_all('table')

for index,table in enumerate(gme_tables):
    if ("GME Quarterly Revenue" in str(table)):
        gme_table_index = index

gme_revenue = pd.DataFrame(columns=["Date", "Revenue"])

for row in gme_tables[tesla_table_index].tbody.find_all("tr"):
    col = row.find_all("td")
    if (col !=[]):
        date = col[0].text
        revenue = col[1].text.replace("$", "").replace(",", "")
        gme_revenue = gme_revenue.append({"Date" : date, "Revenue" : revenue}, ignore_index=True)

<details><summary>Click here if you need help locating the table</summary>

```
    
Below is the code to isolate the table, you will now need to loop through the rows and columns like in the previous lab
    
soup.find_all("tbody")[1]
    
If you want to use the read_html function the table is located at index 1


```

</details>

Display the last five rows of the `gme_revenue` dataframe using the `tail` function. Take a screenshot of the results.

In [61]:
gme_revenue.tail(5)

          Date Revenue
57  2006-01-31    1667
58  2005-10-31     534
59  2005-07-31     416
60  2005-04-30     475
61  2005-01-31     709

## Question 5: Plot Tesla Stock Graph

Use the `make_graph` function to graph the Tesla Stock Data, also provide a title for the graph. The structure to call the `make_graph` function is `make_graph(tesla_data, tesla_revenue, 'Tesla')`. Note the graph will only show data upto June 2021.

In [20]:
make_graph (tesla_data, tesla_revenue, 'Tesla Stock Data')

## Question 6: Plot GameStop Stock Graph

Use the `make_graph` function to graph the GameStop Stock Data, also provide a title for the graph. The structure to call the `make_graph` function is `make_graph(gme_data, gme_revenue, 'GameStop')`. Note the graph will only show data upto June 2021.

In [ ]:
make_graph (gme_data, gme_revenue, 'GameStop Stock Data')

<h2>About the Authors:</h2> 

<a href="https://www.linkedin.com/in/joseph-s-50398b136/">Joseph Santarcangelo</a> has a PhD in Electrical Engineering, his research focused on using machine learning, signal processing, and computer vision to determine how videos impact human cognition. Joseph has been working for IBM since he completed his PhD.

Azim Hirjani

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By    | Change Description        |
| ----------------- | ------- | ------------- | ------------------------- |
| 2022-02-28        | 1.2     | Lakshmi Holla | Changed the URL of GameStop |
| 2020-11-10        | 1.1     | Malika Singla | Deleted the Optional part |
| 2020-08-27        | 1.0     | Malika Singla | Added lab to GitLab       |

<hr>

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>

<p>